### ISSUE TITLE
Simplify local setup process

### ISSUE THREAD

**Issue by Lenni009** [NMSCD/NMSCD.github.io-Redesign#12]
Couldn't we in theory change the `npm run setup` command to also run `npm i`? Or do you need to run `setup` more than once?

**Comment by Khaoz-Topsy** [comment]
I think it is possible, the only issue I see is that if we change the setup script to `"npm i && <some-other-cmd>"` there might be some situations where it doesn't work. I tried it in CMD, Powershell and Bash and it worked no problem. Something in the back of my mind is screaming that it doesn't always work but I can't remember in what scenario it doesn't work 🤔. 

Lets give it a try 😝
